### ISSUE TITLE
Get feedback from Nick on TypeScript environment

### ISSUE THREAD

**Issue by mattdsteele** [mattdsteele/advent-of-code#1]
Hey @nicknisi!

Just gonna open an issue here as I try figuring this stuff out, slightly higher fidelity than Twitter!

So! I've got a basic setup up & running in this repo.

I'm gonna write tests & production code in TypeScript.

My tools:
- Typescript 1.7.3
- tsc via `tsconfig.json`, typings through `tsd.json`; a postinstall hook runs `tsd install`
- Source code in `src/`, test in `test/`, JS compiiled into `built/[src|test]`
- Using neovim with `typescript-vim` plugin (no customizations)
- Mocha for tests
- npm scripts to actually run things; might add Grunt/Gulp later

My workflow right now is to run `npm test`, it has a hook to run `tsc` followed by `mocha`.

A few questions I've got about a TS env:
- Any useful way to speed things up? Right now `npm test` takes three seconds to do basically nothing; I feel like it could be faster.
- Are you compiling/getting feedback directly in vim? The `typescript-vim` plugin's docs say I can run `:make`, but I get this error:
  ![image](https://cloud.githubusercontent.com/assets/389077/11614604/f0f3208e-9c0c-11e5-8c1f-f61b375f5506.png)
- If you are getting feedback in neovim, any secrets to making it async?
- Is there a better way to handle the typings pragma? It's kind of a pain to have to type the `/// <reference` stuff
- Any other pain points I should be aware of, or stuff you wish was handled better?

**Comment by mattdsteele** [comment]
Here's another question: how do I use ES6 collections like `Set` and `WeakMap`? I'm running in Node 5 so they're available natively, but when I try to run `let x = new Set()` TSC complains with `Cannot find name 'Set'`.

**Comment by nicknisi** [comment]
Apologies, I'm bad at Github and just saw this. I'll take a look and respond this evening.

**Comment by mattdsteele** [comment]
No rush, I'm working on other projects the rest of the week!

On Mon, Dec 7, 2015 at 12:20 PM -0800, "Nick Nisi" notifications@github.com wrote:

Apologies, I'm bad at Github and just saw this. I'll take a look and respond this evening.

**Comment by mattdsteele** [comment]
Switching to golang, so hot right now

**Comment by nicknisi** [comment]
I'm the worst at Github.
